### ISSUE TITLE
Probe.condition is unused

### ISSUE THREAD

**Issue by thomasmorgan** [Ruben222/Social-learning-spite#1]
```    @property
    def condition(self):
        return json.loads(self.property2)["condition"]
```

**Comment by thomasmorgan** [comment]
but it is being set, so maybe everything is ok.

**Comment by thomasmorgan** [comment]
Ditto for Partnerscore

**Comment by thomasmorgan** [comment]
In general storing single value JSONs in the multiple property columns is overkill. Either store the values directly in each column (without any JSONing) or store them all in a single JSON in a single column. @Ruben222 any preference?

**Comment by Rowatsonn** [comment]
No, I don't have any strong preference here. I know you could just put them in the same column but I ended up splitting them up because I felt it was simpler for me (even though I know it isn't!).

I'm not sure what you mean by being able to set them without JSON though, I wasn't aware you could do that. How would I do that?

**Comment by thomasmorgan** [comment]
You only need JSON when you want to put multiple values in the same column. If you have just one value per column the properties and setters are enough. I've updated your experiment to use just this:

d3217680ce2c464ea8456b9d9d52c85891dec64c
58afbc0b41a8d6e842fcebd864a0d42d0d927002
63d9a8c3888d4cb2defcf9059f0ccfabb1c66445
65ab75034e6bd670b7c3a66e7fd5a22fb90d0575

**Comment by thomasmorgan** [comment]
This issue appears to be fixed, so I will close it.
